### ISSUE TITLE
Just a query

### ISSUE THREAD

**Issue by Sahil-Gulihar** [bennetthardwick/dotfiles#5]
Why do you need yt-dlp as a dependancy?
Are you making an alias of that youtube downloader or is it just some bloat?

**Comment by bennetthardwick** [comment]
Hey @Sahil-Gulihar - I use `yt-dlp` to download videos from time to time. The `.yt-dlp/` config folder specifies where the videos I download should go, what the name of the downloaded file should be and where to get cookies from. It's not bloat because I use it! 😄
